[[Map]]
	name = "testMap001"
	ele0 = "grass1"
	ele1 = "fwall1"
	ele2 = "fwall2"
	ele3 = "testWall"
	ele4 = "fgate1"
	data = """
	ele0*null*0*@TextBox*2*2,ele0*null*0*null*null*null,ele0*null*0*null*null*null,ele0*null*0*null*null*null,ele0*null*0*@*null*null,@,
	ele0*null*0*null*null*null,ele0*null*0*null*null*null,ele0*null*0*null*null*null,ele0*null*0*null*null*null,ele0*null*0*null*null*null,@,
	ele0*null*0*null*null*null,ele0*null*0*null*null*null,ele0*$ele1$ele2$ele3$ele4*0*null*null*null,ele0*null*0*null*null*null,ele0*null*0*null*null*null,@,
	ele0*null*0*null*null*null,ele0*null*0*null*null*null,ele0*null*0*null*null*null,ele0*null*0*null*null*null,ele0*null*0*null*null*null,@,
	ele0*null*0*@@*null*null,ele0*null*0*null*null*null,ele0*null*0*null*null*null,ele0*null*0*null*null*null,ele0*null*0*@ESC@*null*null,@,
	"""
