[[SystemString]]
	lang = "en"
	configSave = "save"
	configLoad = "load"
	selectScenario = "scenario"
	selectScenario2 = "other"
	selectChara1 = "Please select a character to play"
	DoYouWantToQuitTheGame = "Do you want to quit the game"
